# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
compute_weighted_interactions <- function(H, cards, dc, target) {
    .Call(`_genet_compute_weighted_interactions`, H, cards, dc, target)
}

initialize_root <- function(mapped_interactions, target) {
    .Call(`_genet_initialize_root`, mapped_interactions, target)
}

#' @noRd
update_J_and_f <- function(J, f, interactions, root, target) {
    invisible(.Call(`_genet_update_J_and_f`, J, f, interactions, root, target))
}

#' @noRd
check_convergence <- function(not_converged, diff_root, f, eps) {
    invisible(.Call(`_genet_check_convergence`, not_converged, diff_root, f, eps))
}

#' @noRd
MNR <- function(interactions, root_ini, target, eps = 10^(-5), verbose = FALSE, max_ite = 100L) {
    .Call(`_genet_MNR`, interactions, root_ini, target, eps, verbose, max_ite)
}

add_edges <- function(edge_list, last_edge, n_edges, endpoints) {
    invisible(.Call(`_genet_add_edges`, edge_list, last_edge, n_edges, endpoints))
}

sample_endpoints <- function(i, j, n_edges, cards, leaders) {
    .Call(`_genet_sample_endpoints`, i, j, n_edges, cards, leaders)
}

rBKN <- function(cards, H, root, verbose = FALSE, way_too_verbose = FALSE) {
    .Call(`_genet_rBKN`, cards, H, root, verbose, way_too_verbose)
}

